services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    hostname: homeassistant
    volumes:
      - ${HOMEASSISTANT_CONFIG_FOLDER:-./config}:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TZ: ${TIMEZONE}
    restart: always
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    networks:
      external:
        ipv4_address: ${HOMEASSISTANT_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}